/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_conv3D */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_conv3D
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_conv3D
#ifdef __cplusplus
extern "C" {
#endif
#undef z_dragon_engine_cuda_impl_math_Cuda_conv3D_max_streamsize
#define z_dragon_engine_cuda_impl_math_Cuda_conv3D_max_streamsize 10L
#undef z_dragon_engine_cuda_impl_math_Cuda_conv3D_max_grid
#define z_dragon_engine_cuda_impl_math_Cuda_conv3D_max_grid 65535L
#undef z_dragon_engine_cuda_impl_math_Cuda_conv3D_grid_slice
#define z_dragon_engine_cuda_impl_math_Cuda_conv3D_grid_slice 32768L
#undef z_dragon_engine_cuda_impl_math_Cuda_conv3D_IM2COL_GEMM
#define z_dragon_engine_cuda_impl_math_Cuda_conv3D_IM2COL_GEMM 1L
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D
	 * Signature: ([JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_texture
	 * Signature: ([JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1texture
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_np
	 * Signature: ([JIJIIJIIJIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1np
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_W1
	 * Signature: ([JIJIIJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1W1
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3DV2
	 * Signature: (Z[JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3DV2
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    kernel_remode
	 * Signature: (JJJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_kernel_1remode
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_GemmR
	 * Signature: ([JIJIIJJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1GemmR
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_GemmR_SGM
	 * Signature: ([JIJIIJJIIJIIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1GemmR_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_GemmR_texture
	 * Signature: ([JIJIIJJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1GemmR_1texture
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_GemmR_texture_SGM
	 * Signature: ([JIJIIJJIIJIIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1GemmR_1texture_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_GemmR_W1
	 * Signature: ([JIJIIJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1GemmR_1W1
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_GemmR_W1_SGM
	 * Signature: ([JIJIIJJJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1GemmR_1W1_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jlong, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_GemmV2R
	 * Signature: (Z[JIJIIJJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1GemmV2R
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_Im2col_Winograd_s8_R_texture
	 * Signature: (Z[JIJIIJJIIJIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1Im2col_1Winograd_1s8_1R_1texture
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_Im2col_WinogradR_s8_texture_SGM
	 * Signature: (Z[JIJIIJJIIJIIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1Im2col_1WinogradR_1s8_1texture_1SGM
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_Im2col_Winograd_s16_R_texture
	 * Signature: (Z[JIJIIJJIIJIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1Im2col_1Winograd_1s16_1R_1texture
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_conv3D
	 * Method:    conv3D_Im2col_WinogradR_s16_texture_SGM
	 * Signature: (Z[JIJIIJJIIJIIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1conv3D_conv3D_1Im2col_1WinogradR_1s16_1texture_1SGM
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
