/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX */

#ifndef _Included_z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
#define _Included_z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
#ifdef __cplusplus
extern "C" {
#endif
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_s1
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_s1 10L
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_V2
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_V2 10L
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_KerelSplit
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_KerelSplit 10L
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_CrossAdd
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_streamsize_CrossAdd 7L
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_grid
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_max_grid 65535L
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_grid_slice
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_grid_slice 32768L
#undef z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_IM2COL_GEMM
#define z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX_IM2COL_GEMM 1L
	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_s1
	 * Signature: ([JIJIIJIIJIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1s1
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_s1_SGM
	 * Signature: ([JIJIIJIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1s1_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_s1_texture
	 * Signature: ([JIJIIJIIJIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1s1_1texture
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_s1_texture_SGM
	 * Signature: ([JIJIIJIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1s1_1texture_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_W1
	 * Signature: ([JIJJJIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1W1
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_W1_SGM
	 * Signature: ([JIJJJIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1W1_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_V2_s1
	 * Signature: (Z[JIJIIJIIJIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1V2_1s1
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    ks_remode
	 * Signature: (JJIIJIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_ks_1remode
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    ks_remodev2
	 * Signature: (JJIIJIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_ks_1remodev2
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_kernelSplit
	 * Signature: ([JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1kernelSplit
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_kernelSplit_SGM
	 * Signature: ([JIJIIJIIJIIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1kernelSplit_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksImsR
	 * Signature: ([JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksImsR
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksImsR_SGM
	 * Signature: ([JIJIIJIIJIIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksImsR_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksImsR_texture
	 * Signature: ([JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksImsR_1texture
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksImsR_texture_SGM
	 * Signature: ([JIJIIJIIJIIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksImsR_1texture_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksIms2R
	 * Signature: ([JIJIIJIIJIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksIms2R
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksIms2R_SGM
	 * Signature: ([JIJIIJIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksIms2R_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksIms2R_texture
	 * Signature: ([JIJIIJIIJIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksIms2R_1texture
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksIms2R_texture_SGM
	 * Signature: ([JIJIIJIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksIms2R_1texture_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_ksV2_Ims2R
	 * Signature: (Z[JIJIIJIIJIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1ksV2_1Ims2R
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_crossAdd
	 * Signature: ([JIJIIJIIJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1crossAdd
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    dconv3D_deltaX_crossAdd_SGM
	 * Signature: ([JIJIIJIIJIIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_dconv3D_1deltaX_1crossAdd_1SGM
	(JNIEnv *, jclass, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    Im2col_Winograd_s8_texture
	 * Signature: (Z[JIJIIJIIJIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_Im2col_1Winograd_1s8_1texture
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    Im2col_Winograd_s8_texture_SGM
	 * Signature: (Z[JIJIIJIIJIIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_Im2col_1Winograd_1s8_1texture_1SGM
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    Im2col_Winograd_s16_texture
	 * Signature: (Z[JIJIIJIIJIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_Im2col_1Winograd_1s16_1texture
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_math_Cuda_dconv3D_deltaX
	 * Method:    Im2col_Winograd_s16_texture_SGM
	 * Signature: (Z[JIJIIJIIJIIIIIIII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_z_dragon_engine_cuda_impl_math_Cuda_1dconv3D_1deltaX_Im2col_1Winograd_1s16_1texture_1SGM
	(JNIEnv *, jclass, jboolean, jlongArray, jint, jlong, jint, jint, jlong, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
