/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class z_dragon_engine_cuda_impl_Cuda_expk2 */

#ifndef _Included_z_dragon_engine_cuda_impl_Cuda_expk2
#define _Included_z_dragon_engine_cuda_impl_Cuda_expk2
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    transpose2D
	 * Signature: (JJJIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_transpose2D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    transpose3D
	 * Signature: (JJJIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_transpose3D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    transpose4D
	 * Signature: (JJJIIIIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_transpose4D
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    gappedMemcpy2D
	 * Signature: (JJIIJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_gappedMemcpy2D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    rot180
	 * Signature: (JJJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_rot180
	(JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    srcIndexedMemcpy
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_srcIndexedMemcpy
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    dstIndexedMemcpy
	 * Signature: (JJJJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_dstIndexedMemcpy
	(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    pad2D
	 * Signature: (JJIIJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_pad2D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    pad3D
	 * Signature: (JJIIIJIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_pad3D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    pad4D
	 * Signature: (JJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_pad4D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    trim2D
	 * Signature: (JJIIJIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_trim2D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    trim3D
	 * Signature: (JJIIIJIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_trim3D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    trim4D
	 * Signature: (JJIIIIJIIIIIIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_trim4D
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

	/*
	 * Class:     z_dragon_engine_cuda_impl_Cuda_expk2
	 * Method:    check_mem_alignment
	 * Signature: (JJIII)V
	 */
	JNIEXPORT void JNICALL Java_z_dragon_engine_cuda_impl_Cuda_1expk2_check_1mem_1alignment
	(JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
